# Generated by Django 5.0.6 on 2024-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='templates/pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(upload_to='templates/videos/'),
        ),
    ]
