# Generated by Django 5.0.6 on 2024-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_course_pdf_alter_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
